## The purpose of these functions is to create a matrix that has the ability to Cache its inverse
## as well as the ability to retrieve it's inverse from the Cache.  The idea is that it will save
## processing time by only computing the inverse of the matrix once, rather than each time its needed

## This functions takes an invertible matrix as input and outputs a list of functions.  The function x$set()
## is used to change the stored matrix, it take the new invertible matrix as an arguement and also clears the
## cached inverse.  The x$get() function returns the matrix stored. The x$setinverse() function takes the
## inverse of the matrix as an arguement, and sets the cached inverse of the matrix.  The x$getinverse()
## returns the cached inverse of the matrix, or NULL if none has been cached.

makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## This function takes a list of functions generated by the makeCacheMatrix function as an arguement.
## This function returns the inverse of a makeCacheMatrix by using the solve function.  If an inverse
## of the matrix is cached, it returns it, if not it calculates the inverse, stores it in the cache
## and returns it.

cacheSolve <- function(x, ...) {
    inv <- x$getinverse()
    if(!is.null(inv)){
        message("getting cached data")
        return(inv)
    }
    data <- x$get()
    inv <- solve(data, ...)
    x$setinverse(inv)
    inv
}